version: '2'

services:
  db:
    image: mysql:5.7
    restart: always
    volumes:
        - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: omeka
      MYSQL_DATABASE: omeka
      MYSQL_USER: omeka
      MYSQL_PASSWORD: omeka

  db_admin:
    image: phpmyadmin/phpmyadmin
    restart: always
    links:
     - db:db
    ports:
      - "8080:80"

  omeka-s:
    depends_on:
      - db
    build: ./
    image: jeremyboggs/omeka-s
    ports:
      - "80:80"
    volumes:
      - modules/:/var/www/html/modules/
      - theme/:/var/www/html/themes/custom/
      - item_files/:/var/www/html/files
    restart: always

volumes:
  modules:
  theme:
  item_files:
  mysql-data:
